name:                conv
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/conv#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - conversion
  - conversion-text
  - conversion-bytestring
  - text
  - convertible
  - bytestring
  - convertible
  - convert

executables:
  conv:
    source-dirs:      src
    main:             Main.hs
