resolver: lts-9.3
packages:
  - '.'
  - location:
      git: git@github:wdanilo/convert
      commit: 87082111ad27145687725f45e655a39af057dcaa
    extra-dep: true
extra-deps:
  - conversion-1.2.1
  - conversion-text-1.0.1
  - conversion-bytestring-1.0.1
